### ISSUE TITLE
Pinecone Index

### ISSUE THREAD

**Issue by na8r** [1nnovat1on/gpt_chatbot#3]
You will also need to create an index in Pinecone.

Please provide steps to do this correctly. I've got it running, except it fails. I did setx PINECONEKEY ######, but I get the error, 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\gpt_chatbot\chatbot.py", line 138, in mic
    response = queryOpenAITemplate3(text)
  File "c:\gpt_chatbot\chatbot.py", line 213, in queryOpenAITemplate3
    contexts = retrieve_relevant_metadata(prompt)
  File "c:\gpt_chatbot\chatbot.py", line 295, in retrieve_relevant_metadata
    res = longTermMemory.query(xq, top_k=NUMBER_OF_RELEVANT_THINGS_TO_RETURN_FROM_PINECONE, include_metadata=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\utils\error_handling.py", line 15, in inner_func
    Config.validate()  # raises exceptions in case of invalid config
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\config.py", line 56, in validate
    raise ApiKeyError("You haven't specified an Api-Key.")
pinecone.core.client.exceptions.ApiKeyError: "You haven't specified an Api-Key."

Which is I'm guessing, because I don't know how to set a Pinecone Index. Help please.

**Comment by 1nnovat1on** [comment]
Hello,

I added a brief section on how to create an index. 

In your case, it looks like maybe it couldn't read the API key yet. Check to see if it shows up in your Windows Environment Variables, and restart your command prompt or code editor!

Thanks, let me know if it works!

**Comment by na8r** [comment]
Worked, and its fun. thanks for the info
